FROM httpd:2.4
MAINTAINER Austin West awest1339

ENV PYTHON_VER 3.6.2

COPY ../.. /opt/multiscanner
COPY ./docker/standalone/*.ini /opt/multiscanner/

WORKDIR /opt/multiscanner
RUN ./install.sh

# Run script
CMD python web/app.py
