FROM rabbitmq:3-management
LABEL maintainer="Austin West awest1339"

RUN rabbitmq-plugins enable --offline rabbitmq_tracing rabbitmq_federation rabbitmq_federation_management

EXPOSE 4369 5671 5672 25672 15671 15672
