FROM python:3.6
LABEL maintainer="Austin West awest1339"

ENV PYTHON_VER 3.6.2

COPY . /opt/multiscanner
COPY ./docker/standalone/*.ini /opt/multiscanner/

WORKDIR /opt/multiscanner
RUN ./install.sh

# Run script
# The sleep is a workaround to make extra sure that
# the ElasticSearch container is up before the api
# attempts to connect to it
EXPOSE 8080
CMD sleep 30; python utils/api.py
